language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer validate

install:
  - composer install --prefer-dist

script:
  - php-cs-fixer fix --dry-run
  - phpunit

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
